'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { Itinerary, SpotCard, UserPreferences } from '@/app/page';

interface ItineraryViewProps {
  itinerary: Itinerary;
  preferences: UserPreferences;
  onBack: () => void;
  onVersionSwitch: (version: string) => void;
}

const versions = [
  { id: 'classic', label: '🏖️ 经典版', desc: '平衡体验' },
  { id: 'relax', label: '🌿 轻松版', desc: '减少步行' },
  { id: 'rainy', label: '🌧️ 雨天版', desc: '室内优先' },
  { id: 'photo', label: '📸 拍照版', desc: '出片为主' },
];

export function ItineraryView({ itinerary, preferences, onBack, onVersionSwitch }: ItineraryViewProps) {
  const [activeDay, setActiveDay] = useState(0);
  const [flippedCards, setFlippedCards] = useState<Set<string>>(new Set());
  const [activeVersion, setActiveVersion] = useState('classic');
  const [showAlert, setShowAlert] = useState(true);
  const [viewMode, setViewMode] = useState<'cards' | 'river'>('cards');
  const [revealedLucky, setRevealedLucky] = useState<Set<string>>(new Set());

  const toggleFlip = (id: string) => {
    setFlippedCards((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen pb-24"
    >
      {/* Header */}
      <div className="sticky top-0 z-20 glass-card-strong border-b border-white/60">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-3 sm:py-4">
          <div className="flex items-center justify-between mb-2">
            <button
              onClick={onBack}
              className="text-sm text-primary-600 hover:text-primary-800 flex items-center gap-1 font-medium"
            >
              ← 返回对话
            </button>
            <span className="text-xs bg-gradient-to-r from-primary-50 to-sky-50 text-primary-700 px-3 py-1 rounded-full border border-primary-100/50 font-medium">
              {itinerary.version}
            </span>
          </div>
          <h1 className="text-lg sm:text-xl font-bold text-navy-900">{itinerary.title}</h1>
          {/* Share button */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="mt-2 text-xs bg-gradient-to-r from-violet-50 to-pink-50 border border-violet-100/50 text-violet-700 px-3 py-1.5 rounded-lg font-medium flex items-center gap-1.5"
            onClick={() => {
              // Generate a shareable summary
              const spotsCount = itinerary.days.reduce((a, d) => a + d.spots.length, 0);
              const luckyCount = itinerary.days.reduce((a, d) => a + d.spots.filter(s => s.isLuckySpot).length, 0);
              alert(`🎴 旅行名片已生成！\n\n「${itinerary.title}」\n👤 ${preferences.personality || '探索者'}\n📍 ${spotsCount} 个精选地点\n🎲 ${luckyCount} 个Lucky Spot盲盒\n⚡ 动态适配 · 多版本可切\n\n— Generated by Travel Copilot`);
            }}
          >
            🎴 生成旅行名片
          </motion.button>
        </div>

        {/* Day tabs + view toggle */}
        <div className="max-w-3xl mx-auto px-4 sm:px-6 flex items-center justify-between pb-3">
          <div className="flex gap-2">
            {itinerary.days.map((day, i) => (
              <button
                key={day.dayNumber}
                onClick={() => setActiveDay(i)}
                className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${
                  activeDay === i
                    ? 'bg-gradient-to-r from-primary-500 to-sky-500 text-white shadow-sm'
                    : 'bg-white/70 text-gray-600 hover:bg-white border border-primary-100/30'
                }`}
              >
                Day {day.dayNumber}
              </button>
            ))}
          </div>
          {/* View mode toggle */}
          <div className="flex gap-1 bg-white/60 rounded-lg p-0.5 border border-primary-100/30">
            <button
              onClick={() => setViewMode('cards')}
              className={`text-xs px-2.5 py-1 rounded-md transition-all ${viewMode === 'cards' ? 'bg-white shadow-sm text-primary-700' : 'text-gray-500'}`}
            >
              🃏 卡牌
            </button>
            <button
              onClick={() => setViewMode('river')}
              className={`text-xs px-2.5 py-1 rounded-md transition-all ${viewMode === 'river' ? 'bg-white shadow-sm text-primary-700' : 'text-gray-500'}`}
            >
              🌊 河流
            </button>
          </div>
        </div>
      </div>

      {/* Dynamic Adjustment Alert */}
      <AnimatePresence>
        {showAlert && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="max-w-3xl mx-auto px-4 sm:px-6 mt-4"
          >
            <div className="glass-card rounded-xl p-4 border-l-4 border-l-amber-400">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm font-medium text-amber-700 mb-1">⚡ 动态调整建议</p>
                  <p className="text-xs text-gray-600 leading-relaxed">
                    下午2点气温较高（预计34°C），当前路线连续室外步行2.8小时。建议插入45分钟室内休息点，并减少1个低优先级点位。
                  </p>
                </div>
                <button
                  onClick={() => setShowAlert(false)}
                  className="text-gray-400 hover:text-gray-600 ml-2 text-lg"
                >
                  ✕
                </button>
              </div>

              <div className="flex gap-2 mt-3 flex-wrap">
                {versions.map((v) => (
                  <button
                    key={v.id}
                    onClick={() => {
                      setActiveVersion(v.id);
                      onVersionSwitch(v.label);
                      setShowAlert(false);
                    }}
                    className={`text-xs px-3 py-1.5 rounded-lg transition-all font-medium ${
                      activeVersion === v.id
                        ? 'bg-gradient-to-r from-primary-500 to-sky-500 text-white shadow-sm'
                        : 'bg-white/80 border border-primary-100/50 text-gray-600 hover:border-primary-300'
                    }`}
                  >
                    {v.label}
                  </button>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Energy Curve */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 mt-4">
        <EnergyCurve spots={itinerary.days[activeDay]?.spots || []} />
      </div>

      {/* Content: Cards or River view */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 mt-6">
        {viewMode === 'cards' ? (
          <div className="space-y-4">
            <AnimatePresence>
              {itinerary.days[activeDay]?.spots.map((spot, i) => (
                <motion.div
                  key={spot.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                >
                  <SpotCardComponent
                    spot={spot}
                    isFlipped={flippedCards.has(spot.id)}
                    onFlip={() => toggleFlip(spot.id)}
                    index={i}
                    isRevealed={revealedLucky.has(spot.id)}
                    onReveal={() => setRevealedLucky(prev => new Set(prev).add(spot.id))}
                  />
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        ) : (
          <TimeRiver spots={itinerary.days[activeDay]?.spots || []} />
        )}
      </div>

      {/* Bottom version switcher (persistent) */}
      <div className="fixed bottom-0 left-0 right-0 glass-card-strong border-t border-white/60 py-3 px-4 sm:px-6 z-10">
        <div className="max-w-3xl mx-auto flex gap-2 justify-center">
          {versions.map((v) => (
            <button
              key={v.id}
              onClick={() => {
                setActiveVersion(v.id);
                onVersionSwitch(v.label);
              }}
              className={`text-xs px-3 sm:px-4 py-2 rounded-xl transition-all font-medium ${
                activeVersion === v.id
                  ? 'bg-gradient-to-r from-primary-500 to-sky-500 text-white shadow-sm'
                  : 'bg-white/70 text-gray-600 hover:bg-white border border-primary-100/30'
              }`}
            >
              {v.label}
            </button>
          ))}
        </div>
      </div>
    </motion.div>
  );
}

/* ===== Time River View ===== */
function TimeRiver({ spots }: { spots: SpotCard[] }) {
  return (
    <div className="relative">
      {/* River flowing line */}
      <div className="absolute left-6 sm:left-8 top-0 bottom-0 w-1 river-gradient rounded-full" />

      <div className="space-y-6">
        {spots.map((spot, i) => {
          const isRest = spot.category === '休息';
          const isLucky = spot.isLuckySpot;

          return (
            <motion.div
              key={spot.id}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.1 }}
              className="relative pl-14 sm:pl-16"
            >
              {/* River node */}
              <div className={`absolute left-4 sm:left-6 top-4 w-5 h-5 rounded-full border-2 border-white shadow-md z-10 ${
                isLucky ? 'bg-gradient-to-br from-amber-400 to-orange-400 animate-glow' :
                isRest ? 'bg-gradient-to-br from-emerald-300 to-emerald-400' :
                'bg-gradient-to-br from-primary-400 to-sky-400'
              }`} />

              {/* River width indicator (activity density) */}
              {!isRest && (
                <div className={`absolute left-3 sm:left-5 top-6 w-7 h-full opacity-10 rounded-b-full ${
                  spot.walkingMinutes > 40 ? 'bg-primary-500' : 'bg-primary-300'
                }`} style={{ height: `${Math.min(spot.walkingMinutes * 1.5, 80)}px` }} />
              )}

              {/* Spot content card */}
              <div className={`glass-card rounded-xl p-4 ${
                isLucky ? 'border-amber-200/60 shadow-[0_0_20px_rgba(251,191,36,0.1)]' :
                isRest ? 'border-emerald-100/60' : ''
              }`}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      {isLucky && <span className="text-base">🎲</span>}
                      <h3 className="font-semibold text-navy-900 text-sm sm:text-base truncate">{spot.name}</h3>
                    </div>
                    <p className="text-xs text-gray-500 mb-2">{spot.description}</p>
                    <div className="flex gap-1.5 flex-wrap">
                      <span className="text-[10px] sm:text-xs px-2 py-0.5 rounded-full bg-primary-50 text-primary-600">
                        ⏰ {spot.bestTime}
                      </span>
                      {spot.walkingMinutes > 0 && (
                        <span className="text-[10px] sm:text-xs px-2 py-0.5 rounded-full bg-sky-50 text-sky-600">
                          🚶 {spot.walkingMinutes}min
                        </span>
                      )}
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-lg">{
                      spot.category === '拍照' ? '📸' :
                      spot.category === '美食' ? '🍜' :
                      spot.category === '休息' ? '☕' :
                      spot.category === '文化' ? '🎨' : '📍'
                    }</span>
                  </div>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}

/* ===== Spot Card Component ===== */
function SpotCardComponent({ spot, isFlipped, onFlip, index, isRevealed, onReveal }: { spot: SpotCard; isFlipped: boolean; onFlip: () => void; index: number; isRevealed: boolean; onReveal: () => void }) {
  const getCrowdColor = (level: string) => {
    switch (level) {
      case 'low': return 'text-emerald-600 bg-emerald-50';
      case 'medium': return 'text-amber-600 bg-amber-50';
      case 'high': return 'text-red-600 bg-red-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  };

  const getCrowdLabel = (level: string) => {
    switch (level) {
      case 'low': return '人少';
      case 'medium': return '适中';
      case 'high': return '人多';
      default: return '';
    }
  };

  // Lucky Spot blind box - unrevealed state
  if (spot.isLuckySpot && !isRevealed) {
    return (
      <motion.div
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={onReveal}
        className="cursor-pointer"
      >
        <div className="glass-card rounded-2xl p-6 border-amber-200/60 shadow-[0_0_24px_rgba(251,191,36,0.15)] text-center relative overflow-hidden">
          {/* Shimmer overlay */}
          <div className="absolute inset-0 shimmer-bg" />
          <motion.div
            animate={{ rotate: [0, 10, -10, 0], scale: [1, 1.1, 1] }}
            transition={{ duration: 2, repeat: Infinity }}
            className="text-5xl mb-3"
          >
            🎲
          </motion.div>
          <h3 className="font-bold text-amber-800 text-base mb-1">Lucky Spot 盲盒</h3>
          <p className="text-xs text-amber-600/80">点击揭晓你的专属惊喜地点 ✨</p>
          <div className="flex justify-center gap-1 mt-3">
            {[...Array(3)].map((_, i) => (
              <motion.span
                key={i}
                animate={{ opacity: [0.3, 1, 0.3] }}
                transition={{ duration: 1.5, delay: i * 0.3, repeat: Infinity }}
                className="w-2 h-2 rounded-full bg-amber-400"
              />
            ))}
          </div>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      whileHover={{ y: -2, boxShadow: '0 8px 40px rgba(0, 0, 0, 0.08)' }}
      onClick={onFlip}
      className="cursor-pointer"
    >
      <div className="card-flip">
        <div className={`card-flip-inner ${isFlipped ? 'flipped' : ''} relative`}>
          {/* Front */}
          <div className={`card-front glass-card rounded-2xl p-4 sm:p-5 ${
            spot.isLuckySpot
              ? 'border-amber-200/60 shadow-[0_0_24px_rgba(251,191,36,0.12)]'
              : ''
          }`}>
            <div className="flex items-start justify-between">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  {spot.isLuckySpot && <span className="text-lg animate-pulse-slow">🎲</span>}
                  <h3 className="font-semibold text-navy-900 text-sm sm:text-base">{spot.name}</h3>
                </div>
                <p className="text-xs sm:text-sm text-gray-500 mb-3">{spot.description}</p>

                <div className="flex gap-1.5 flex-wrap">
                  <span className={`text-[10px] sm:text-xs px-2 py-0.5 rounded-full font-medium ${getCrowdColor(spot.crowdLevel)}`}>
                    👥 {getCrowdLabel(spot.crowdLevel)}
                  </span>
                  <span className="text-[10px] sm:text-xs px-2 py-0.5 rounded-full bg-purple-50 text-purple-600 font-medium">
                    📸 {'★'.repeat(spot.photoScore)}{'☆'.repeat(5 - spot.photoScore)}
                  </span>
                  {spot.walkingMinutes > 0 && (
                    <span className="text-[10px] sm:text-xs px-2 py-0.5 rounded-full bg-sky-50 text-sky-600 font-medium">
                      🚶 {spot.walkingMinutes}min
                    </span>
                  )}
                </div>
              </div>
              <span className="text-[10px] sm:text-xs text-primary-400 shrink-0">翻转 →</span>
            </div>
          </div>

          {/* Back */}
          <div className={`card-back absolute inset-0 glass-card rounded-2xl p-4 sm:p-5 ${
            spot.isLuckySpot
              ? 'border-amber-200/60'
              : ''
          }`}>
            <h4 className="text-sm font-semibold text-navy-900 mb-2">🎯 推荐理由</h4>
            <p className="text-xs sm:text-sm text-gray-600 mb-3 leading-relaxed">{spot.reason}</p>

            <div className="space-y-1.5 text-xs text-gray-500">
              <p>⏰ 最佳时段：{spot.bestTime}</p>
              {spot.alternatives.length > 0 && (
                <p>🔄 备选方案：{spot.alternatives.join(' / ')}</p>
              )}
              <p>📂 类型：{spot.category}</p>
            </div>

            <p className="text-[10px] sm:text-xs text-primary-400 mt-3">← 点击翻回</p>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

/* ===== Energy Curve ===== */
function EnergyCurve({ spots }: { spots: SpotCard[] }) {
  const energyData = spots.map((spot) => {
    if (spot.category === '休息') return 20;
    if (spot.category === '美食') return 35;
    if (spot.walkingMinutes > 45) return 85;
    if (spot.walkingMinutes > 30) return 65;
    return 45;
  });

  const maxEnergy = Math.max(...energyData, 1);

  return (
    <div className="glass-card rounded-xl p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-xs font-semibold text-navy-900">📊 能量曲线</h3>
        <span className="text-[10px] sm:text-xs text-gray-400">体力消耗预估</span>
      </div>
      <div className="flex items-end gap-1.5 h-14">
        {energyData.map((energy, i) => (
          <motion.div
            key={i}
            initial={{ height: 0 }}
            animate={{ height: `${(energy / maxEnergy) * 100}%` }}
            transition={{ delay: i * 0.1, duration: 0.5, ease: 'easeOut' }}
            className={`flex-1 rounded-t transition-colors ${
              energy <= 30 ? 'bg-gradient-to-t from-emerald-400 to-emerald-300' :
              energy <= 50 ? 'bg-gradient-to-t from-sky-400 to-sky-300' :
              energy <= 70 ? 'bg-gradient-to-t from-amber-400 to-amber-300' :
              'bg-gradient-to-t from-rose-400 to-rose-300'
            }`}
            title={spots[i]?.name}
          />
        ))}
      </div>
      <div className="flex gap-1.5 mt-1.5">
        {spots.map((spot, i) => (
          <div key={i} className="flex-1 text-center">
            <span className="text-[9px] sm:text-[10px] text-gray-400 truncate block leading-tight">
              {spot.name.slice(0, 3)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
